
### /projects/{projectId}/milestone
POST http://localhost:8080/projects/2/milestone
Content-Type: application/json

{
  "name": "hello"
}


### /projects/{projectId}/milestone
GET http://localhost:8080/projects/2/milestone
Content-Type: application/json

### /projects/milestone/{milestoneId}
GET http://localhost:8080/projects/milestone/3
Content-Type: application/json

### /projects/{projectId}/milestone/{milestoneId}
PUT http://localhost:8080/projects/2/milestone/3
Content-Type: application/json

{
  "name" : "test"
}


### /projects/milestone/{milestoneId}
DELETE http://localhost:8080/projects/milestone/12418
Content-Type: application/json
