

### /project/{projectId}

GET http://localhost:8080/projects/1
Content-Type: application/json



### /project
POST http://localhost:8080/projects
Content-Type: application/json

{
  "userId": "200",
  "projectStatusId": 1,
  "title": "13213"
}


### /project/{projectId}
PUT http://localhost:8080/projects/1
Content-Type: application/json

{
  "userId": "100",
  "projectStatusId": 1,
  "title": "aaqewqwezxc"
}

### /project/{projectId}
DELETE http://localhost:8080/projects/1
Content-Type: application/json

